In [46]:
import numpy as np
import pandas as pd

문제1

1-1 플롯 차트(plot chart)

1-2 plot(x,y)

문제2

2-1 if의 조건식이 True일 경우 if의 실행문장을 실행하고 끝난다. False일 경우, elif 조건식을 검사하여 True이면 elif의 실행문장을 실행하고 끝난다. elif의 조건식도 False일 경우, else의 실행문장을 실행하고 끝난다.

2-2 while문은 반복횟수가 명확하지 않을 때 사용한다. 예를 들어 한쪽이 가위바위보를 이길때까지 반복하는 경우이다.
for문은 반복횟수가 명확할 때 사용한다. 예를 들어 우리반 출석을 부를 때, 우리반 전체 인원이란 명확한 반복 횟수가 있는 경우이다.

In [2]:
# 문제 3
list1= [1,50,27,19,37,33,5,3,48]
even=0
odd=0
for i in list1:
    if i%2==0:
        even+=1
    else:
        odd+=1
print(f"짝수 {even}개, 홀수 {odd}개")

짝수 2개, 홀수 7개

In [122]:
# 문제 4
score_list=[['김미희',89,78,99],
            ['서대희',67,88,77],
            ['강예진',100,55,96]]

# DF로 변환
noName=[]
for i in range(len(score_list)):
    noName.append(score_list[i][1:])
noName

name=[]
for i in range(len(score_list)):
    name.append(score_list[i][0])
name

col=['Python','Java','DB']

scoreDF=pd.DataFrame(noName) #index=name,columns=col
scoreDF

# 평균 계산
scoreDF['평균'] =scoreDF.sum(axis=1)//len(scoreDF.columns)
scoreDF

# 과목별 평균
# print(f"{(scoreDF.sum()//len(scoreDF))[0]}")

#학점
print("================================================")
print('이름','Python','Java','DB','평균','학점',sep='\t')
print("================================================")
for i in range(len(scoreDF)):
    if scoreDF['평균'][i] >=90:
        abc='A'
    elif scoreDF['평균'][i] >=80:
        abc='B'
    elif scoreDF['평균'][i] >=70:
        abc='C'
    elif scoreDF['평균'][i] >=60:
        abc='D'
    else:
        abc='F'
    print(name[i],scoreDF.iloc[i,0],scoreDF.iloc[i,1],scoreDF.iloc[i,2],scoreDF.iloc[i,3],abc,sep="\t")
print("================================================")
print('평균',(scoreDF.sum()//len(scoreDF))[0],(scoreDF.sum()//len(scoreDF))[1],(scoreDF.sum()//len(scoreDF))[2],sep='\t')

================================================
이름	Python	Java	DB	평균	학점
================================================
김미희	89	78	99	88	B
서대희	67	88	77	77	C
강예진	100	55	96	83	B
================================================
평균	85	73	90

In [52]:
# 문제 5
movie = np.genfromtxt('lib/data/ratings.dat',delimiter='::',dtype=np.int64)

movieId= np.unique(movie[:,1])
np.sort(movieId)

movieMeanList=[]
for i in movieId:
    movieMean=movie[movie[:,1]==i][:,2].mean()
    movieMeanList.append([i,movieMean])

movieMeanList

[[1, 4.146846413095811],
 [2, 3.20114122681883],
 [3, 3.01673640167364],
 [4, 2.7294117647058824],
 [5, 3.0067567567567566],
 [6, 3.8787234042553194],
 [7, 3.410480349344978],
 [8, 3.014705882352941],
 [9, 2.656862745098039],
 [10, 3.5405405405405403],
 [11, 3.7938044530493706],
 [12, 2.3625],
 [13, 3.2626262626262625],
 [14, 3.542483660130719],
 [15, 2.458904109589041],
 [16, 3.7932551319648096],
 [17, 4.027544910179641],
 [18, 3.337579617834395],
 [19, 2.480719794344473],
 [20, 2.5375],
 [21, 3.6238938053097347],
 [22, 3.3492063492063493],
 [23, 2.857142857142857],
 [24, 3.1794871794871793],
 [25, 3.6510204081632653],
 [26, 3.53],
 [27, 2.9344262295081966],
 [28, 4.055865921787709],
 [29, 4.062034739454094],
 [30, 3.6486486486486487],
 [31, 3.1134751773049647],
 [32, 3.945731303772336],
 [33, 3.0],
 [34, 3.8914905768132497],
 [35, 3.3142857142857145],
 [36, 3.9579741379310347],
 [37, 3.5],
 [38, 2.8214285714285716],
 [39, 3.6233480176211454],
 [40, 3.933333333333333],
 [41, 3.958677685950413],
 [42, 2.8687782805429864],
 [43, 3.4457831325301207],
 [44, 2.787781350482315],
 [45, 3.4246323529411766],
 [46, 3.108433734939759],
 [47, 4.106420404573439],
 [48, 2.9764397905759163],
 [49, 3.740740740740741],
 [50, 4.517106001121705],
 [52, 3.640371229698376],
 [53, 4.75],
 [54, 2.5609756097560976],
 [55, 3.066666666666667],
 [56, 2.0],
 [57, 3.404040404040404],
 [58, 4.093812375249501],
 [59, 2.75],
 [60, 3.212885154061625],
 [61, 3.0],
 [62, 3.6968576709796674],
 [63, 2.855855855855856],
 [64, 2.2658227848101267],
 [65, 2.062937062937063],
 [66, 1.6701030927835052],
 [67, 3.25],
 [68, 3.45],
 [69, 3.6551724137931036],
 [70, 3.1564551422319473],
 [71, 2.1041666666666665],
 [72, 3.6344086021505375],
 [73, 3.8169642857142856],
 [74, 2.975],
 [75, 1.9166666666666667],
 [76, 2.853932584269663],
 [77, 3.764705882352941],
 [78, 3.26],
 [79, 2.6052631578947367],
 [80, 3.826923076923077],
 [81, 3.1626506024096384],
 [82, 3.8764044943820224],
 [83, 3.696969696969697],
 [84, 3.0952380952380953],
 [85, 3.402061855670103],
 [86, 3.3940677966101696],
 [87, 2.210526315789474],
 [88, 2.9427083333333335],
 [89, 3.074235807860262],
 [90, 3.6666666666666665],
 [92, 2.340909090909091],
 [93, 2.235955056179775],
 [94, 3.7252747252747254],
 [95, 2.876175548589342],
 [96, 3.923076923076923],
 [97, 3.75],
 [98, 2.0],
 [99, 3.46],
 [100, 3.0625],
 [101, 3.869565217391304],
 [102, 1.8166666666666667],
 [103, 3.212121212121212],
 [104, 3.526392961876833],
 [105, 3.2325581395348837],
 [106, 3.5833333333333335],
 [107, 3.1484375],
 [108, 2.857142857142857],
 [110, 4.234957020057307],
 [111, 4.183870967741935],
 [112, 3.443859649122807],
 [113, 2.981132075471698],
 [114, 3.090909090909091],
 [116, 4.097560975609756],
 [117, 3.632911392405063],
 [118, 3.073529411764706],
 [119, 2.4615384615384617],
 [120, 2.6666666666666665],
 [121, 4.054054054054054],
 [122, 2.768041237113402],
 [123, 3.869565217391304],
 [124, 3.2142857142857144],
 [125, 3.8333333333333335],
 [126, 1.9898989898989898],
 [127, 1.0],
 [128, 4.333333333333333],
 [129, 3.3076923076923075],
 [130, 4.0],
 [131, 3.0625],
 [132, 2.4945054945054945],
 [133, 1.0],
 [134, 4.0],
 [135, 2.81203007518797],
 [136, 3.25],
 [137, 3.0],
 [138, 2.5],
 [139, 4.0],
 [140, 3.1654676258992804],
 [141, 3.5498533724340176],
 [142, 1.0],
 [144, 3.392609699769053],
 [145, 3.2955801104972378],
 [146, 2.888888888888889],
 [147, 3.541436464088398],
 [148, 2.782608695652174],
 [149, 3.7872340425531914],
 [150, 4.073541167066347],
 [151, 3.588447653429603],
 [152, 3.0],
 [153, 2.642213642213642],
 [154, 3.7261904761904763],
 [155, 3.413793103448276],
 [156, 3.5606060606060606],
 [157, 2.732620320855615],
 [158, 2.9806949806949805],
 [159, 3.2844827586206895],
 [160, 2.2389380530973453],
 [161, 3.723684210526316],
 [162, 4.063136456211812],
 [163, 3.4574074074074073],
 [164, 3.5672823218997363],
 [165, 3.561212121212121],
 [166, 2.459016393442623],
 [167, 3.6],
 [168, 2.9502762430939224],
 [169, 2.017699115044248],
 [170, 3.146417445482866],
 [171, 3.5698924731182795],
 [172, 2.576419213973799],
 [173, 2.3085106382978724],
 [174, 2.308641975308642],
 [175, 3.477272727272727],
 [176, 3.9170731707317072],
 [177, 2.7338129496402876],
 [178, 3.473684210526316],
 [179, 2.2083333333333335],
 [180, 3.5476718403547673],
 [181, 1.6129032258064515],
 [182, 3.142857142857143],
 [183, 3.4827586206896552],
 [184, 3.3461538461538463],
 [185, 2.869947275922671],
 [186, 2.7630331753554502],
 [187, 3.238095238095238],
 [188, 3.221052631578947],
 [189, 3.4],
 [190, 3.75],
 [191, 2.466666666666667],
 [192, 3.0],
 [193, 2.0506912442396312],
 [194, 3.755868544600939],
 [195, 2.841463414634146],
 [196, 2.8236363636363637],
 [197, 3.0588235294117645],
 [198, 3.2958677685950413],
 [199, 3.8119658119658117],
 [200, 2.4166666666666665],
 [201, 2.6363636363636362],
 [202, 2.5],
 [203, 3.0541871921182264],
 [204, 2.9211822660098523],
 [205, 3.611764705882353],
 [206, 3.6707317073170733],
 [207, 3.132420091324201],
 [208, 2.6313364055299537],
 [209, 2.4615384615384617],
 [210, 3.1463414634146343],
 [211, 3.5588235294117645],
 [212, 1.9285714285714286],
 [213, 4.056910569105691],
 [214, 4.25],
 [215, 3.80625],
 [216, 3.183098591549296],
 [217, 2.625],
 [218, 3.128205128205128],
 [219, 3.1818181818181817],
 [220, 1.8214285714285714],
 [222, 3.547112462006079],
 [223, 3.946883852691218],
 [224, 3.3911917098445596],
 [225, 3.173228346456693],
 [226, 2.0],
 [227, 2.6744186046511627],
 [228, 2.1538461538461537],
 [229, 3.5],
 [230, 3.4527220630372493],
 [231, 3.1924242424242424],
 [232, 4.07514450867052],
 [233, 3.6127659574468085],
 [234, 2.2244897959183674],
 [235, 3.696871628910464],
 [236, 3.303680981595092],
 [237, 2.972762645914397],
 [238, 2.8125],
 [239, 2.875],
 [240, 2.7111111111111112],
 [241, 3.310344827586207],
 [242, 3.5],
 [243, 2.1],
 [244, 1.9],
 [245, 3.0],
 [246, 4.18854748603352],
 [247, 3.8658280922431865],
 [248, 2.9130434782608696],
 [249, 3.7586206896551726],
 [250, 2.6],
 [251, 3.2777777777777777],
 [252, 3.2697547683923704],
 [253, 3.524390243902439],
 [254, 3.0789473684210527],
 [255, 2.0606060606060606],
 [256, 2.6513761467889907],
 [257, 3.2280701754385963],
 [258, 2.423611111111111],
 [259, 2.843137254901961],
 [260, 4.453694416583082],
 [261, 3.6491228070175437],
 [262, 3.872093023255814],
 [263, 3.857142857142857],
 [264, 3.2],
 [265, 3.9326424870466323],
 [266, 3.425531914893617],
 [267, 2.7285714285714286],
 [268, 3.3703703703703702],
 [269, 3.5272727272727273],
 [270, 3.037974683544304],
 [271, 3.142857142857143],
 [272, 3.7258485639686683],
 [273, 2.8975409836065573],
 [274, 2.375],
 [275, 2.5375],
 [276, 2.692982456140351],
 [277, 3.1823529411764704],
 [278, 2.75],
 [279, 3.717391304347826],
 [280, 3.5707547169811322],
 [281, 3.648068669527897],
 [282, 3.2232558139534886],
 [283, 3.0],
 [286, 3.0],
 [287, 2.9047619047619047],
 [288, 3.144285714285714],
 [289, 3.3417721518987342],
 [290, 3.9166666666666665],
 [291, 2.2083333333333335],
 [292, 3.2687585266030013],
 [293, 4.106175514626218],
 [294, 3.0952380952380953],
 [295, 2.7586206896551726],
 [296, 4.278212805158913],
 [297, 3.107142857142857],
 [298, 3.9130434782608696],
 [299, 3.664335664335664],
 [300, 3.7588652482269502],
 [301, 3.302325581395349],
 [302, 3.813953488372093],
 [303, 2.9760765550239237],
 [304, 3.142857142857143],
 [305, 2.5039370078740157],
 [306, 4.227544910179641],
 [307, 4.098765432098766],
 [308, 3.9653465346534653],
 [309, 3.6875],
 [310, 2.6666666666666665],
 [311, 3.0],
 [312, 2.4375],
 [313, 2.888888888888889],
 [314, 3.85],
 [315, 2.65359477124183],
 [316, 3.490143369175627],
 [317, 3.1918876755070205],
 [318, 4.554557700942973],
 [319, 3.8937728937728937],
 [320, 3.40625],
 [321, 3.7540983606557377],
 [322, 3.712918660287081],
 [324, 3.9696969696969697],
 [325, 2.4489795918367347],
 [326, 4.344262295081967],
 [327, 2.6145251396648046],
 [328, 3.111111111111111],
 [329, 3.3767676767676766],
 [330, 2.7315436241610738],
 [331, 3.0952380952380953],
 [332, 2.546583850931677],
 [333, 3.502439024390244],
 [334, 3.8596491228070176],
 [335, 3.4878048780487805],
 [336, 2.6842105263157894],
 [337, 3.8412698412698414],
 [338, 2.8823529411764706],
 [339, 3.49925705794948],
 [340, 3.2738095238095237],
 [341, 3.838709677419355],
 [342, 3.6776061776061777],
 [343, 2.4285714285714284],
 [344, 3.1488250652741514],
 [345, 3.8059701492537314],
 [346, 3.525],
 [347, 3.1739130434782608],
 [348, 3.698901098901099],
 [349, 3.7261567516525025],
 [350, 3.392233009708738],
 [351, 3.342412451361868],
 [352, 3.134453781512605],
 [353, 3.4455040871934606],
 [354, 3.1791044776119404],
 [355, 2.352059925093633],
 [356, 4.087967183226983],
 [357, 3.7437145174371453],
 [358, 3.1702127659574466],
 [359, 3.210526315789474],
 [360, 2.4960629921259843],
 [361, 3.421641791044776],
 [362, 3.3640167364016738],
 [363, 4.258064516129032],
 [364, 3.8608385370205176],
 [365, 3.1690140845070425],
 [366, 2.8207171314741037],
 [367, 3.279050042408821],
 [368, 3.5236907730673317],
 [369, 3.310344827586207],
 [370, 2.8980582524271843],
 [371, 3.1792452830188678],
 [372, 3.1542056074766354],
 [373, 3.856589147286822],
 [374, 2.1147540983606556],
 [375, 3.2941176470588234],
 [376, 3.2457142857142856],
 [377, 3.5654545454545454],
 [378, 2.892857142857143],
 [379, 2.889908256880734],
 [380, 3.6342857142857143],
 [381, 3.2606635071090047],
 [382, 2.9338235294117645],
 [383, 3.2666666666666666],
 [384, 2.9],
 [385, 3.4],
 [386, 2.6],
 [387, 2.7450980392156863],
 [388, 3.6391752577319587],
 [389, 3.7],
 [390, 3.542372881355932],
 [391, 3.275],
 [392, 2.8],
 [393, 1.8571428571428572],
 [394, 3.6666666666666665],
 [396, 4.0],
 [397, 2.4166666666666665],
 [398, 4.0],
 [401, 3.0],
 [402, 3.0],
 [404, 3.75],
 [405, 2.123152709359606],
 [406, 3.625],
 [407, 2.911917098445596],
 [408, 3.3194444444444446],
 [409, 3.020408163265306],
 [410, 2.9071274298056156],
 [411, 2.6153846153846154],
 [412, 3.559322033898305],
 [413, 2.5306122448979593],
 [414, 2.6555555555555554],
 [415, 2.4804469273743015],
 [416, 2.4269662921348316],
 [417, 3.485576923076923],
 [418, 2.5172413793103448],
 [419, 2.1923076923076925],
 [420, 2.5056818181818183],
 [421, 3.3617021276595747],
 [422, 3.1228070175438596],
 [423, 3.1085972850678734],
 [424, 2.6],
 [425, 3.6095238095238096],
 [426, 3.0817843866171004],
 [427, 2.3674698795180724],
 [428, 3.931558935361217],
 [429, 2.379679144385027],
 [430, 2.4166666666666665],
 [431, 3.6910569105691056],
 [432, 2.579081632653061],
 [433, 2.7916666666666665],
 [434, 3.0845481049562684],
 [435, 2.6060037523452158],
 [436, 2.652482269503546],
 [437, 2.046875],
 [438, 2.625],
 [439, 4.5],
 [440, 3.811181434599156],
 [441, 3.6936236391912907],
 [442, 2.9921875],
 [443, 3.3870967741935485],
 [444, 2.2962962962962963],
 [445, 2.61],
 [446, 4.082677165354331],
 [447, 2.4838709677419355],
 [448, 3.6008771929824563],
 [449, 3.6619718309859155],
 [450, 3.280701754385965],
 [451, 3.150943396226415],
 [452, 3.289473684210526],
 [453, 3.2238805970149254],
 [454, 3.5473300970873787],
 [455, 2.5894736842105264],
 [456, 4.0],
 [457, 4.103258145363409],
 [458, 3.2758620689655173],
 [459, 2.832167832167832],
 [460, 2.263157894736842],
 [461, 3.2790697674418605],
 [462, 2.642857142857143],
 [463, 2.74468085106383],
 [464, 2.7824074074074074],
 [465, 3.3142857142857145],
 [466, 2.7958115183246073],
 [467, 3.2037037037037037],
 [468, 3.2714285714285714],
 [469, 2.9565217391304346],
 [470, 1.736842105263158],
 [471, 3.631051752921536],
 [472, 2.7045454545454546],
 [473, 2.225165562913907],
 [474, 3.825102880658436],
 [475, 3.9006410256410255],
 [476, 2.6857142857142855],
 [477, 3.466666666666667],
 [478, 2.4583333333333335],
 [479, 2.7969924812030076],
 [480, 3.7638473053892216],
 [481, 3.380952380952381],
 [482, 3.528409090909091],
 [483, 3.7432432432432434],
 [484, 2.6551724137931036],
 [485, 2.508],
 [486, 2.8125],
 [487, 2.6129032258064515],
 [488, 3.3846153846153846],
 [489, 2.4742268041237114],
 [490, 3.324324324324324],
 [491, 3.3160377358490565],
 [492, 3.719402985074627],
 [493, 3.6073825503355703],
 [494, 3.3461538461538463],
 [495, 3.380952380952381],
 [496, 3.2162162162162162],
 [497, 4.0],
 [498, 2.74468085106383],
 [499, 2.7551020408163267],
 [500, 3.420047732696897],
 [501, 3.606382978723404],
 [502, 1.935483870967742],
 [503, 3.6923076923076925],
 [504, 2.955056179775281],
 [505, 2.4927536231884058],
 [506, 3.491228070175439],
 [507, 3.522727272727273],
 [508, 3.894830659536542],
 [509, 3.674342105263158],
 [510, 2.4047619047619047],
 [511, 3.1052631578947367],
 [512, 2.8715083798882683],
 [513, 3.1194029850746268],
 [514, 3.531791907514451],
 [515, 3.917777777777778],
 [516, 2.870967741935484],
 [517, 3.175392670157068],
 [518, 2.4563758389261743],
 [519, 1.9405940594059405],
 [520, 2.93048128342246],
 [521, 3.3675213675213675],
 [522, 3.566265060240964],
 [523, 3.658119658119658],
 [524, 3.615546218487395],
 [525, 3.1904761904761907],
 [526, 2.5],
 [527, 4.510416666666667],
 [528, 2.514705882352941],
 [529, 3.977777777777778],
 [530, 3.5],
 [531, 3.769230769230769],
 [532, 3.0488431876606685],
 [533, 2.7339901477832513],
 [534, 3.835664335664336],
 [535, 3.8172757475083055],
 [536, 3.1636363636363636],
 [537, 3.077294685990338],
 [538, 3.8222222222222224],
 [539, 3.760649087221095],
 [540, 2.2189349112426036],
 [541, 4.273333333333333],
 [542, 2.674757281553398],
 [543, 3.3841642228739004],
 [544, 2.643410852713178],
 [545, 2.0],
 [546, 1.8742857142857143],
 [547, 2.879032258064516],
 [548, 2.5474452554744524],
 [549, 3.821656050955414],
 [550, 3.0168539325842696],
 [551, 3.717871485943775],
 [552, 3.2400756143667295],
 [553, 3.8734177215189876],
 [554, 2.6153846153846154],
 [555, 3.9285714285714284],
 [556, 4.2272727272727275],
 [557, 4.5],
 [558, 2.7037037037037037],
 [559, 3.0],
 [560, 3.625],
 [561, 3.6153846153846154],
 [562, 3.799163179916318],
 [563, 3.235294117647059],
 [564, 2.2666666666666666],
 [565, 3.1311475409836067],
 [566, 2.923076923076923],
 [567, 3.5714285714285716],
 [568, 3.857142857142857],
 [569, 2.93],
 [570, 3.217391304347826],
 [571, 3.588235294117647],
 [572, 3.0],
 [573, 3.5238095238095237],
 [574, 3.4457142857142857],
 [575, 2.822429906542056],
 [576, 3.0],
 [577, 2.963636363636364],
 [578, 4.5],
 [579, 2.0],
 [580, 3.2419354838709675],
 [581, 4.049645390070922],
 [582, 3.0],
 [583, 3.6785714285714284],
 [584, 4.0],
 [585, 2.9066985645933014],
 [586, 3.1348148148148147],
 [587, 3.49644128113879],
 [588, 3.788304959289415],
 [589, 4.058512646281616],
 [590, 3.9152308752584424],
 [591, 2.0],
 [592, 3.6009783368273935],
 [593, 4.3518231186966645],
 [594, 3.8453473132372213],
 [595, 3.8858490566037736],
 [596, 3.751004016064257],
 [597, 3.641491395793499],
 [598, 4.25],
 [599, 4.087121212121212],
 [600, 3.0],
 [601, 3.0],
 [602, 4.121951219512195],
 [603, 3.0],
 [605, 3.314159292035398],
 [606, 2.225806451612903],
 [607, 2.0],
 [608, 4.254675686430561],
 [609, 2.7761194029850746],
 [610, 3.546925566343042],
 [611, 2.4722222222222223],
 [612, 2.4050632911392404],
 [613, 3.6341463414634148],
 [614, 2.6666666666666665],
 [615, 4.044776119402985],
 [616, 3.352517985611511],
 [617, 3.6470588235294117],
 [618, 2.111111111111111],
 [619, 2.59375],
 [621, 3.7142857142857144],
 [623, 3.0],
 [624, 4.0],
 [626, 2.263157894736842],
 [627, 3.603305785123967],
 [628, 3.8969072164948453],
 [630, 2.857142857142857],
 [631, 2.08],
 [632, 4.0],
 [633, 3.6],
 [634, 1.6666666666666667],
 [635, 3.6233766233766236],
 [637, 2.5428571428571427],
 [638, 3.210526315789474],
 [639, 2.6153846153846154],
 [640, 2.676056338028169],
 [641, 1.0],
 [642, 2.0],
 [643, 2.0],
 [644, 2.0],
 [645, 3.6],
 [647, 3.5532879818594103],
 [648, 3.432874918140144],
 [649, 4.1875],
 [650, 3.4719101123595504],
 [651, 2.0],
 [652, 2.888888888888889],
 [653, 3.2254901960784315],
 [655, 1.0],
 [656, 2.5641025641025643],
 [657, 3.0],
 [658, 3.0],
 [659, 3.72],
 [660, 1.5],
 [661, 3.4647619047619047],
 [662, 2.984375],
 [663, 3.4166666666666665],
 [664, 3.0],
 [665, 3.657142857142857],
 [666, 3.3333333333333335],
 [667, 2.0425531914893615],
 [668, 4.404255319148936],
 [669, 4.173913043478261],
 [670, 4.410714285714286],
 [671, 3.6798245614035086],
 [672, 2.0],
 [673, 2.619893428063943],
 [674, 3.0155440414507773],
 [678, 4.245098039215686],
 [679, 3.5],
 [680, 3.359375],
 [681, 3.933333333333333],
 [682, 3.5],
 [684, 1.0],
 [685, 3.3],
 [687, 3.0],
 [688, 2.276995305164319],
 [690, 2.0],
 [691, 3.0991735537190084],
 [692, 2.1132075471698113],
 [694, 2.645390070921986],
 [695, 3.1777777777777776],
 [696, 3.25],
 [697, 2.552941176470588],
 [698, 2.2],
 [700, 3.3241379310344827],
 [701, 4.0],
 [702, 3.6666666666666665],
 [703, 1.6],
 [704, 2.3095238095238093],
 [705, 3.8333333333333335],
 [706, 2.5],
 [707, 3.0872727272727274],
 [708, 3.434462444771723],
 [709, 3.0416666666666665],
 [710, 2.3333333333333335],
 [711, 2.5],
 [712, 3.5],
 [714, 3.888888888888889],
 [715, 3.6153846153846154],
 [716, 2.6785714285714284],
 [717, 4.0],
 [718, 3.484848484848485],
 [719, 2.8619246861924688],
 [720, 4.426940639269406],
 [722, 3.814814814814815],
 [724, 3.0865384615384617],
 [725, 2.791208791208791],
 [726, 3.0],
 [728, 3.7649769585253456],
 [729, 3.6666666666666665],
 [730, 1.0],
 [731, 2.851063829787234],
 [732, 2.8333333333333335],
 [733, 3.723134328358209],
 [734, 3.0],
 [735, 3.3564356435643563],
 [736, 3.1738738738738737],
 [737, 2.03],
 [741, 4.089171974522293],
 [742, 2.528735632183908],
 [743, 2.5700934579439254],
 [744, 2.0],
 [745, 4.52054794520548],
 [746, 4.0],
 [747, 2.0],
 [748, 3.1510791366906474],
 [749, 2.75],
 [750, 4.4498902706656915],
 [751, 3.533333333333333],
 [753, 3.15625],
 [754, 2.923076923076923],
 [755, 3.7777777777777777],
 [756, 3.0],
 [757, 3.75],
 [758, 4.0],
 [759, 4.101694915254237],
 [760, 3.515151515151515],
 [761, 2.7886178861788617],
 [762, 2.184563758389262],
 [763, 3.0],
 [764, 3.27027027027027],
 [765, 2.6315789473684212],
 [766, 3.57],
 [767, 3.2083333333333335],
 [769, 3.25],
 [771, 3.7777777777777777],
 [774, 4.0],
 [775, 3.2222222222222223],
 [776, 3.0],
 [778, 3.9600532623169107],
 [779, 2.6923076923076925],
 [780, 3.5104046242774567],
 [781, 3.378640776699029],
 [782, 2.5517241379310347],
 [783, 3.223076923076923],
 [784, 2.72987012987013],
 [785, 3.4784313725490197],
 [786, 3.123913043478261],
 [787, 5.0],
 [788, 2.9957805907172994],
 [789, 3.0],
 [790, 3.0],
 [791, 3.5],
 [792, 4.0],
 [793, 2.6],
 [796, 3.3333333333333335],
 [798, 2.7058823529411766],
 [799, 3.3491124260355027],
 [800, 4.082539682539682],
 [801, 3.0991735537190084],
 [802, 3.496487119437939],
 [803, 3.6842105263157894],
 [804, 2.9785407725321886],
 [805, 3.5901162790697674],
 [806, 3.1666666666666665],
 [807, 3.0],
 [808, 3.395348837209302],
 [809, 2.5714285714285716],
 [810, 1.4666666666666666],
 [811, 3.888888888888889],
 [813, 2.5106382978723403],
 [814, 3.0],
 [815, 2.0],
 [818, 2.560846560846561],
 [820, 3.25],
 [821, 2.0],
 [823, 3.25],
 [824, 3.9285714285714284],
 [826, 1.0],
 [827, 3.0],
 [828, 2.9074074074074074],
 [829, 2.2900763358778624],
 [830, 2.952542372881356],
 [831, 3.85],
 [832, 3.478723404255319],
 [833, 2.1794871794871793],
 [834, 2.0],
 [835, 3.1262135922330097],
 [836, 2.654008438818565],
 [837, 3.477064220183486],
 [838, 3.8802395209580838],
 [839, 2.214814814814815],
 [840, 2.56],
 [841, 3.4],
 [842, 2.589403973509934],
 [843, 1.0],
 [844, 3.5714285714285716],
 [846, 3.736842105263158],
 [847, 1.8571428571428572],
 [848, 3.4358974358974357],
 [849, 2.5107632093933465],
 [850, 3.6666666666666665],
 [851, 3.4960629921259843],
 [852, 3.221138211382114],
 [853, 4.0],
 [854, 3.625],
 [858, 4.524966261808367],
 [859, 2.0],
 [860, 3.6],
 [861, 3.5128205128205128],
 [862, 3.6451612903225805],
 [863, 3.5],
 [864, 3.5833333333333335],
 [865, 2.0],
 [866, 3.8234265734265733],
 [867, 2.2083333333333335],
 [868, 3.0],
 [869, 3.0952380952380953],
 [870, 2.183673469387755],
 [872, 3.0],
 [874, 3.125],
 [875, 3.3863636363636362],
 [876, 2.857142857142857],
 [877, 3.2916666666666665],
 [878, 4.0],

In [40]:
# 문제 6-1
data = [[65,44,76,87],
      [55,80,66,85],
      [90,79,58,100],
      [83,42,82,94],
      [44,78,60,90]]
ind= ['DB', 'JAVA','PYTHON','HTML','JS']
col= ['A반','B반','C반','D반']

df=pd.DataFrame(data, index=ind, columns= col)

df

        A반  B반  C반   D반
DB      65  44  76   87
JAVA    55  80  66   85
PYTHON  90  79  58  100
HTML    83  42  82   94
JS      44  78  60   90

In [62]:
# 문제 6-2
df.loc['총합']= df[:'JS'].sum()
df.loc['평균'] =df.loc['총합']//len(df[:'JS'])

df

         A반   B반   C반   D반
DB       65   44   76   87
JAVA     55   80   66   85
PYTHON   90   79   58  100
HTML     83   42   82   94
JS       44   78   60   90
총합      337  323  342  456
평균       67   64   68   91

밑은 연습장입니다!

In [124]:
# 문제 4
score_list=[['김미희',89,78,99],
            ['서대희',67,88,77],
            ['강예진',100,55,96],
           ['차현석',75,100,60]]

# DF로 변환
noName=[]
for i in range(len(score_list)):
    noName.append(score_list[i][1:])
noName

name=[]
for i in range(len(score_list)):
    name.append(score_list[i][0])
name

col=['Python','Java','DB']

scoreDF=pd.DataFrame(noName) #index=name,columns=col
scoreDF

# 평균 계산
scoreDF['평균'] =scoreDF.sum(axis=1)//len(scoreDF.columns)
scoreDF

# 과목별 평균
# print(f"{(scoreDF.sum()//len(scoreDF))[0]}")

#학점
print("================================================")
print('이름','Python','Java','DB','평균','학점',sep='\t')
print("================================================")
for i in range(len(scoreDF)):
    if scoreDF['평균'][i] >=90:
        abc='A'
    elif scoreDF['평균'][i] >=80:
        abc='B'
    elif scoreDF['평균'][i] >=70:
        abc='C'
    elif scoreDF['평균'][i] >=60:
        abc='D'
    else:
        abc='F'
    print(name[i],scoreDF.iloc[i,0],scoreDF.iloc[i,1],scoreDF.iloc[i,2],scoreDF.iloc[i,3],abc,sep="\t")
print("================================================")
print('평균',(scoreDF.sum()//len(scoreDF))[0],(scoreDF.sum()//len(scoreDF))[1],(scoreDF.sum()//len(scoreDF))[2],sep='\t')

================================================
이름	Python	Java	DB	평균	학점
================================================
김미희	89	78	99	88	B
서대희	67	88	77	77	C
강예진	100	55	96	83	B
차현석	75	100	60	78	C
================================================
평균	82	80	83

In [55]:
# movieId= np.unique(movie[:,1])
# np.sort(movieId)

In [ ]:
# movie[:,1]==i #이게 조건식
# movieId=movie[movie[:,1]==i]
# movieId[:,2]

In [54]:
# movieMeanList=[]
# for i in movieId:
#     movieMean=movie[movie[:,1]==i][:,2].mean()
#     movieMeanList.append([i,movieMean])

# movieMeanList

In [66]:
score_list=[['김미희',89,78,99],
            ['서대희',67,88,77],
            ['강예진',100,55,96]]

score_list

[['김미희', 89, 78, 99], ['서대희', 67, 88, 77], ['강예진', 100, 55, 96]]

In [107]:
noName=[]
for i in range(len(score_list)):
    noName.append(score_list[i][1:])
noName

name=[]
for i in range(len(score_list)):
    name.append(score_list[i][0])
name

col=['Python','Java','DB']

scoreDF=pd.DataFrame(noName) #index=name,columns=col
scoreDF

     0   1   2
0   89  78  99
1   67  88  77
2  100  55  96

In [108]:
scoreDF['평균'] =scoreDF.sum(axis=1)//len(scoreDF.columns)
scoreDF

     0   1   2  평균
0   89  78  99  88
1   67  88  77  77
2  100  55  96  83

In [111]:
print(f"{(scoreDF.sum()//len(scoreDF))[0]}")

85

In [121]:
#학점
print("======================================")
print(f"이름    Python  Java  DB   평균   학점",end="\n======================================\n")
for i in range(len(scoreDF)):
    if scoreDF['평균'][i] >=90:
        abc='A'
    elif scoreDF['평균'][i] >=80:
        abc='B'
    elif scoreDF['평균'][i] >=70:
        abc='C'
    elif scoreDF['평균'][i] >=60:
        abc='D'
    else:
        abc='F'
    print(f"{name[i]}    {scoreDF.iloc[i,0]}   {scoreDF.iloc[i,1]}   {scoreDF.iloc[i,2]}   {scoreDF.iloc[i,3]}   {abc}",sep='\t')
print("======================================")
print(f"평균      {(scoreDF.sum()//len(scoreDF))[0]}   {(scoreDF.sum()//len(scoreDF))[1]}   {(scoreDF.sum()//len(scoreDF))[2]}")
#print(f"학점 {abc}",end="\n======================================\n")

======================================
이름    Python  Java  DB   평균   학점
======================================
김미희    89   78   99   88   B
서대희    67   88   77   77   C
강예진    100   55   96   83   B
======================================
평균      85   73   90

In [119]:
#학점
print("================================================")
print('이름','Python','Java','DB','평균','학점',sep='\t')
print("================================================")
for i in range(len(scoreDF)):
    if scoreDF['평균'][i] >=90:
        abc='A'
    elif scoreDF['평균'][i] >=80:
        abc='B'
    elif scoreDF['평균'][i] >=70:
        abc='C'
    elif scoreDF['평균'][i] >=60:
        abc='D'
    else:
        abc='F'
    print(name[i],scoreDF.iloc[i,0],scoreDF.iloc[i,1],scoreDF.iloc[i,2],scoreDF.iloc[i,3],abc,sep="\t")
print("================================================")
print('평균',(scoreDF.sum()//len(scoreDF))[0],(scoreDF.sum()//len(scoreDF))[1],(scoreDF.sum()//len(scoreDF))[2],sep='\t')

================================================
이름	Python	Java	DB	평균	학점
================================================
김미희	89	78	99	88	B
서대희	67	88	77	77	C
강예진	100	55	96	83	B
================================================
평균	85	73	90

In [63]:
scoreDF=pd.DataFrame(score_list)
scoreDF
scoreDF.loc['평균'] =scoreDF[1,2,3].sum()//len(scoreDF)

     0    1   2   3
0  서대희   67  88  77
1  강예진  100  55  96

In [ ]:
df.loc['총합']= df[:'JS'].sum()
df.loc['평균'] =df.loc['총합']//len(df[:'JS'])

df

In [ ]:

scoreDF=pd.DataFrame(score_list)